services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WernerDweight\DoctrineCascadeSoftDeleteBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Exception}'

    WernerDweight\DoctrineCascadeSoftDeleteBundle\EventListener\CascadeSoftDeleteListener:
        tags:
            - { name: doctrine.event_listener, event: preRemove, priority: 16 }
